spring:
  application:
    name: tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/fitnessTracker
    username: postgres
    password: Admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/