spring:
  application:
    name: activity-service
  config:
    import: optional:configserver:http://localhost:8889


rabbitmq:
  queue:
    name: activity_queue
  exchange:
    name: activity_exchange
  routing:
    key: activity_routing_key
